# Studi di prognosi e studi eziologici

L'obiettivo degli *studi di prognosi* e' individuare quali caratteristiche del paziente con una certa diagnosi siano associate con gli esiti durante il decorso della malattia. Questi fattori, come per es. l'eta’, la storia clinica, le caratteristiche della malattia (es. stadio del tumore), eventuali comorbidita’ ecc. si dicono *fattori prognostici*. Per esempio: e’ il livello pressione intracranica pz ricoverati per trauma cranico associato con morte? E’ il braden score piu' elevato associato con lesioni da pressione nel pz ricoverato in terapia intensiva? I fattori prognostici non devono necessariamente causare l’esito ma devono essere in grado di predirlo con un certo grado di approssimazione. 

L'obiettivo degli *studi eziologici* e' individuare quali caratteristiche degli individui all'interno di una popolazione siano associate con il rischio di un certo esito. Queste caratteristiche come per esempio il livello di colesterolo, l'obesita', il fumo di sigaretta ecc. si dicono fattori di rischio. Per esempio: e’ una certa dieta collegata con lo sviluppo di obesita’ negli adolescenti? Le donne immigrate sono piu’ a rischio di non effettuare screening oncologici? e’ il bere alcolici compulsivamente (binge) un comportamento a rischio per le malattie sessualmente trasmesse?

Quindi le principali differenze tra uno studio prognostico ed uno eziologico sono:

- I partecipanti sono differenti: negli studi di prognosi siamo interessati a chi ha una certa diagnosi, negli eziologici a chi ancora non la ha

- Gli esiti sono diversi: lo studio eziologico predice il rischio di una patologia, quello prognostico i diversi esiti (conseguenze) di quella patologia

- I fattori associati con il rischio di sviluppare una malattia non necessariamente sono gli stessi di quelli che indicano una migliore/peggiore esito di quella malattia

Gli studi epidemiologici adatti a rispondere ai quesiti prognostici e a quelli eziologici sono gli studi analitici. Si differenziano per il diverso timing nela quale sono misurate esposizione ed esito. Negli *studi di corte* prima determino l’esposizione (possesso fattore di rischio o prognostico) e poi misuro gli esiti in studio durante il follow-up. Negli *studi caso controllo* prima determino gli esiti in studio e poi misuro retrospettivamente l’esposizione (possesso fattore di rischio o prognostico) durante il followup. Infine, negli *studi trasversali* determino gli esiti in studio e l’esposizione (possesso fattore di rischio o prognostico) nello stesso momento.

## Studi di corte
In epidemiologia una coorte è un gruppo di individui che viene seguito per un periodo di tempo (tempo di follow-up), con lo scopo di valutare ciò che accade loro, in termini di esiti di salute. Negli studi di corte si selezionano gli individui elegibili, che inizialmente non hanno l'esito di interesse, e si dividono in gruppi che differiscono per lo status di esposizione ad alcuni fattori ri rischio (studi eziologici) o per il possesso di fattori prognostici (studi prognostici). Gli individui che fanno parte dei diversi gruppi di esposizione vengono quindi seguiti nel tempo al fine di confrontare l'incidenza degli esiti al termine del follow-up. 
Uno studio di corte molto famoso e' lo studio sulla salute degli infermieri (Nurse Health Study) condotto negli Stati Uniti, una tra le più grandi indagini sui fattori di rischio per le principali malattie croniche nelle donne che e' tutt'ora in corso. Piu' di 120000 infermiere hanno partecipato alla prima corte ed i risultati dell'analisi condotte hanno contribuito a quantificare l'associazione tra fumo, esercizio fisico, obesita', uso di contraccettivi orali e terapie ormonali con numerose patologie cronico degenerative (tra e quali diabete tipo 2, malattie cardiovascolari, cancro dalla mammella, del pancreas e del colon-retto, psoriasi e la sclerosi multipla). 

### Descrizione
{figura}

**Definizione di coorte**. Il termine coorte indica un gruppo designato di persone che viene seguito nel tempo.
Deriva dal latino cohors che indicava una delle 10 divisioni della legione romana. Gli studi di coorte sono anche detti studi di follow up, di incidenza o longitudinali. Come per le altre tipologie di studi, il protocollo dello studio deve essere stato approvato dal comitato etico competente.
    
Negli _studi corte prospettici_ nel momento in cui inizia lo studio, inizia anche il followup. La popolazione in studio viene assegnata al gruppo esposto e a quello di riferimento e si effettua il monitoraggio degli esiti durante il followup. Si immagini di voler determinare l'associazione tra uno score Braden alto e l'insorgenza di piaghe da decubito durante il ricovero in un certo reparto. In uno studio prospettico i pz, tutti senza lesioni al momento dell'inizio della degenza, vengono divisi in due gruppi a seconda del Braden score (braden alto/basso) e l'esito ("insorgenza di lesioni") viene monitorato durante le successive 4 settimane. 

Negli _Studi coorte retrospettivi_ si ricostruisce retrospettivamente la storia dell'esposizione e degli esiti nella popolazione in studio. Quando inizia lo studio il followup e' gia' terminato. Uno studio retrospettivo per determinare l'associazione tra uno score Braden alto e l'insorgenza di piaghe da decubito durante il ricovero in un certo reparto si basa su informazioni gia' raccolte durante i ricoveri (per es. le cartelle cliniche). Dalla lettura di queste informazioni possiamo suddividere al momento del ricovero i pazienti nei due gruppi (score Braden alto e basso) e poi confrontare il numero di pz nei quali siano insorte le lesioni nelle successive 4 settimane.

**Criteri di inclusione ed esclusione**.  Sono le caratteristiche che devono avere i pz per essere inclusi nello studio. Uno dei requisiti di base di uno studio di tipo di coorte è che nessuno dei soggetti ha gia' l'esito di interesse all'inizio del periodo di follow-up. 
Negli studi di prognosi, i pz devono essere selezionati nella stessa fase del decorso della malattia. Per es. pazienti che hanno subito un particolare tipo di trattamento (interventi chirurgici, dialisi ecc.). 
Negli studi eziologici, i partecipanti spesso sono reclutati tra la popolazione generale, come per es. individui che sono portatori di alcuni fattori di rischio (ipertensione, alto colesterolo, BPCO, mutazioni genetiche ecc.) o con stili di vita a rischio (fumo, dieta, comportamenti sessuali etc.). 
Sono ovviamente esclusi tutti gli individui che presentano gia' la condizione patologica sotto indagine all'inizio dello studio (baseline) o perche' non possono sviluppare l'esito durante il followup. Ad esempio, se si volesse confrontare il rischio di sviluppare un cancro all'utero tra le donne in menopausa che ricevono una terapia ormonale sostitutiva con quelle che non ricevono ormoni, dei possibili criteri di inclusione sono: 1) sesso femminile 2) in menopausa e 3) che non hanno subito una isterectomia. 

**Valutazione dell’esposizione**. Negli studi di corte, i partecipanti sono raggruppati in base al possesso o meno di un fattore di rischio (es. possesso alterazione genetica BRCA1 per tumore al seno), in base a diversi livelli di un marcatore (es. Pressione sistolica bassa, media, alta) che pensiamo essere collegato con una diversa prognosi (studi di prognosi), in base alle risposte ottenute da questionari ed interviste (per stili di vita come il tabagismo o la dieta iperlipidica). Lo status di esposizione se possibile viene tenuto nascosto ai verificatori dell’esito. 
   
**Esito e follow up**. L’esito e’ misurabile tramite certificati morte, cartelle cliniche, schede dimissioni ospedaliere, questionari, diagnostica ecc. Durante il follow up i due gruppi (esposti e non esposti) sono monitorati continuamente per gli esiti studiati. Non ci devono essere differenze di accertamento (capacita’ diagnostica). La durata del follow up dipende dagli obiettivi dello studio. In generale il tempo di followup deve essere sufficientemente lungo e completo da permettere l'insorgenza degli esiti studiati. Tuttavia, piu' e' lungo il followup, speso maggiori sono gli abbandoni dei pz (pz *persi al followup*) collegate con il peggioramento delle condizioni di salute.

### Risultati negli studi di corte

Negli studi di corte le misure di frequenza degli esiti sono l'incidenza (o rischio) quando l'esito e' quantificato con una variabile dicotomica e la media quando quantificato con una variabile continua.

$$Incidenza = \frac{Numero\ \ casi\ \ durante\ \ followup}{Numero\ \ pz\ \ che\ \ hanno\ \ iniziato \ \  followup}$$

La tabella di contigenza nel caso di esposizione ed esito entrambe quantificate mediante variabili dicotomiche

|Gruppo |Esito|Non Esito|Tot|
|:---|:---|:---|:---|
|Esposti|a|b|a+b|
|Non esposti|c|d|c+d|
|Tot |a+c|b+d|a+b+c+d|


Da cui segue che:

>
>Incidenza (o rischio) nel gruppo esposto 
>
>$$R1 = \frac{a}{(a+b)}$$
>
> Dove a e' il numero di casi durante il followup nel gruppo esposto e (a+b) e' il numero di individui che hanno iniziato il followup nel gruppo esposto
>
> Incidenza (o rischio) nel gruppo non esposto
>
>$$R0 = \frac{c}{(c+d)}$$
>
> Dove c e' il numero di casi durante il followup nel gruppo di non esposto e (c+d) e' il numero di individui che hanno iniziato il followup nel gruppo non esposto
>

Per misurare l'associazione tra esposizione ed esito si pu' calcolare il rischio relativo ($RR$), la differenza dei rischi o la differenza dei valori medi.

Il *rischio relativo* ($RR$) e':

$$ RR = \frac{ R1 }{R0}$$

Dove:

R1: Incidenza esito nel gruppo esposto

R0: Incidenza esito nel gruppo non esposto

Indica di quante volte è più grande (o piu’ piccola) l’incidenza di esito nel gruppo esposto rispetto a quella misurata nel gruppo non esposto.

La differenza dei rischi ($RD$) e':

$$ RD = { R1 -R0}$$


Dove:

R1: Incidenza esito nel gruppo esposto

R0: Incidenza esito nel gruppo non esposto

Indica la differenza in valori assoluti dell’incidenza di esito nel gruppo esposto rispetto a quella misurata nel gruppo non esposto. 

Quando l'esito viene quantificato tramite variabile continua, il confronto tra i due gruppi deve essere effettuato tramite un confronto tra medie. La differenza risultante esprimera' in termini assoluti la differenza nei valori della variabile di esito.

Tutte le considerazioni legate al calcolo ed interpretazione dell'intervallo di confidenza delle misure di associazione degli studi di corte (RR, RD e differenza delle medie) sono gia' state fatte nel capitolo studi sperimentali.

### Bias studi di corte

Gli errori sistematici causano una distorsione della stima dell’associazione tra esposizione ed esito. Sono di tre tipi: bias di selezione, bias di informazione e confondimento.

**Bias di selezione**. Puo’ essere commesso durante la fase di selezione dei soggetti o durante il follow up e riguarda errori nella selezione o nel mantenimento all'interno dello studio dei partecipanti. Gli studi di corte sono particolarmente soggetti al bias di perdite al followup che si verifica quando si ha un maggior numero di individui che abbandonano lo studio in uno dei due gruppi a confronto. Per es. in uno studio prospettico sull'essociazione tra obesita' e rischio cardiovascolare chi non e' obeso (cioe' non esposto) potrebbe avere meno motivazioni a proseguire il followup smettendo di partecipare al monitoraggio. Quindi in questo gruppo potremmo avere una sottostima del rischio di esito perche' gli eventuali esiti cardovascolari di questi soggetti non sarebbero registrati, aumentando la differenza tra esposti e non esposti.  

**Bias di informazione**. Riguarda tutti gli errori commessi durante la fase di raccolta dati. Riguarda errori nella misura o valutazione dell’esposizione o dell’esito. Un esempio e' il bias di classificazione che comprende gli errori di compilazione dei registri utilizzati come fonte del dato, come per es errori nell'assegnazione dei codici di diagnosi di malattia. 
Il bias di accertamento e' un altro tipo di bias di informazione e riguarda la differente capacita’ di accertamento dell'esito tra gli esposti. Per es. i portatori di un fattore di rischio potrebbero venire sottoposti ad analisi piu' approfondite. In questo caso avremmo una maggiore probabilita' di "scoprire" eventuali malattie in un gruppo rispetto all'altro, aumentando "artificialmente" l'effetto dell'esposizione sull'esito (ovvero la differenza tra esposti e non esposti).

**Confondimento**. Una variabile confondente distorce il valore della misura di associazione tra esposizione ed esito portandoci a conclusioni erronee. E' quindi molto importante evitare che la nostra stima di associazione sia viziata dal confondimento. L’effetto della variabile confondente sulla relazione esposizione-effetto oggetto dello studio puo' causare:

- che l’associazione sia significativa anche quando in realta' non lo e'

- che l’associazione (che in realtà esiste) risulti non significativa

- che la misura di associazione sia sotto- (o sovra-) stimata

Una variabile confondente e' associata con l'esposizione e con l'esito, puo' determinare l'esito anche in assenza dell'esposizione e non e' una variabile intermedia nel modello concettuale che lega l'esposizione all'esito.

A differenza dei bias di selezione e del bias di informazione, che possono essere introdotti dallo sperimentatore o dai partecipanti, il confondimento è un tipo di bias che può essere gestito nell'analisi dei risultati, a condizione che gli investigatori abbiano misurato le eventuali variabili confondenti.

Per esempio l'eta' e' un confondente dell'associazione tra le variazioni emodinamiche (ipo / iper tensione) e il rischio di cadute in ambiente domestico. In questo esempio l'esito di interesse sono le cadute e l'esposizione sono gli sbalzi pressori. Poiche' l'anziano presenta con piu' probabilita' alterazioni emodinamiche, l'eta' risulta collegata con il rischio di cadute. Si noti che avere capogiri non puo' essere un confondente della associazione tra variazioni emodinamiche e caduta perche' anello intermedio nella catena di eventi tra esposizione ed esito (alterazione emodinamica -> capogiro -> caduta). 

Per determinare con esattezza l'effetto delle variazioni pressorie sul rischio di caduta, dobbiamo annullare l'effetto dell'eta'. In altre parole dobbiamo analizzare l'associazione _a parita' di eta'_, selezionando solamente pz con eta' simile. In questo modo misuriamo l'associazione in strati omogenei per eta'. Questo approccio (*analisi stratificata*) permette di ottenere delle stime dell'associazione tra esposizione ed esito che non siano viziate dal confondimento dovuto alla variabile per la quale si stratifica (nell'esempio l'eta'). Si noti che per effettuare l'analisi stratificata per eta', devo averla registrata.

### Vantaggi/svantaggi studi coorte

Gli studi di corte sono il modello di studio epidemiologico piu' efficiente per rispondere a quesiti eziologici o che riguardano la prognosi.

Vantaggi:

- E' relativamente facile essere sicuri che l'esposizione abbia preceduto l'esito

- Sono efficienti per esposizioni rare

- Possono valutare L’associazione di diversi esiti con la stessa esposizione

- Permettono misura diretta dell’incidenza


Svantaggi:

- Inefficienti per esiti rari

- Se retrospettivi, l’informazione sull’esposizione (e altre variabili chiave) può essere di bassa qualità e più soggetta a bias

- Se prospettici sono costosi e di lunga durata (specialmente per malattie con lungo tempo di latenza) e piu’ soggetti alle perdite al followup
 
 
### Esempio di studio di corte

   
## Studi caso controllo
In EBN, gli studi caso-controllo vengono utilizzati per rispondere a quesiti di tipo eziologico o a quesiti di prognosi analogamente agli studi di corte. Sono studi nei quali i pazienti (casi) sono identificati e arruolati nello studio insieme ad un campione (controlli) della popolazione che ha dato origine ai casi. 
Nello studio caso-controllo non è previsto un periodo di follow-up. Si inizia identificando i soggetti malati e si determina quanti di loro sono esposti. Si identificano poi dei controlli selezionando un campione della popolazione dal quale sono originati i casi e si determina quanto di loro sono esposti. Per determinare se esiste una associazione tra esposizione ed esito si confronta il rapporto tra esposti e non esposti tra i casi con quello calcolato tra i controlli. Questa misura si chiama _odds ratio_.
Un esempio di studio caso-controllo riguarda l'individuazione dei potenziali fattori di rischio di caduta in un ospedale degli Stati Uniti (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1490065/). In questo studio 98 pz che erano caduti durante il ricovero e 318 pz che non erano caduti come controllo. La presenza dei fattori di rischio e' stata determinata tramite interviste e l'analisi delle cartelle cliniche. Lo studio ha concluso che lo stato di salute del paziente, in particolare l'andatura anormale o problemi agli arti inferiori, i farmaci e i fattori correlati alla cura, aumentano il rischio di cadute.

### Descrizione


   
{figura}

 tutto quello che c’e’ da sapere sui c-c
• disegno studio caso controllo
• selezione dei controlli
• risultati di uno studio c-c: odds, OR
• principali errori sistematici (bias) degli studi di c-c
• vantaggi/ svantaggi c-c
• valutazione critica studi c-c
   
**Selezione dei casi e dei controlli**.
Come per le altre tipologie di studi, vengono applicati dei criteri di inclusione ed esclusione che devono essere descritti nel protocollo dello studio, sottomesso ed approvato dal comitato etico dell'azienda sanitaria competente prima dell'inizio dello studio. I casi sono di solito arruolati in ambito ospedaliero tra coloro che presentano una determinata patologia (studi _caso-controllo ospedalieri_); meno spesso vengono effettuati su popolazioni non ospedalizzate (studi _caso-controllo comunitari_). 
Uno studio caso-controllo comunitario i casi provengono da una popolazione definita con precisione, come un'area geografica fissa, ei controlli sono campionati direttamente dalla stessa popolazione. In questa situazione, i casi potrebbero essere identificati da un registro statale (del cancro, per esempio) ed il gruppo di confronto sarebbe logicamente selezionato a caso dalla stessa popolazione di origine. I controlli comunitari possono essere identificati per es. dagli elenchi di iscritti alle ASL, o dalle liste elettorali. I controlli della popolazione possono anche essere più difficili da ottenere, tuttavia, a causa della mancanza di interesse a partecipare da parte di individui apparentemente sani.
Il gruppo di controllo ha lo scopo di determinare la relativa proporzione di esposti e non esposti nella popolazione. Gli individui che fanno parte del gruppo di controllo devono quindi essere un campione della stessa popolazione dalla quale sono stati selezionati anche i casi.
Un'altra caratteristica dei controlli e' che devono essere selezionati indipendentemente dal livello di esposizione della quale vogliamo verificare l'associazione con l'esito. Per questo motivo si evita di selezionare gli i controlli da reparti ospedalieri dove il motivo del ricovero sono patologie che hanno fattori di rischio/prognostici in comune con l'esposizione oggetto dello studio. Se per esempio l'oggetto dello studio fosse una ipotetica associazione tra fumo di sigaretta e ipertensione, i casi potrebbero essere reclutati negli ambulatori per la cura dell'ipertensione mentre sarebbe errato selezionare i controlli tra i pazienti normotesi del reparto di pneumologia dello stesso ospedale. In questo ipotetico esempio, in entrambi i gruppi a confronto (casi ipertesi e controlli normotesi) ci sarebbe un rapporto fumatori/non fumatori molto simile portando a concludere erroneamente che il fumo non e' un fattore di rischio per l'ipertensione.
    
**Attribuzione dell’esposizione**
Negli studi caso-controllo l’attribuzione dell’esposizione ai soggetti inclusi nello studio viene fatta retrospettivamente ed e' quindi piu’ soggetta ad errori (bias di informazione, si veda in seguito). Quando possibile si usano le informazioni presenti nelle cartelle cliniche, nelle schede di dimissione ospedaliera o in altri registri, altrimenti si utilizzano questionari o interviste.
   
### Risultati negli studi caso-controllo
Il numero di casi e controlli inclusi nello studio e’ una scelta arbitraria effettuata da chi conduce lo studio. Per questo motivo non e' possibile con questo disegno dello studio quantificare l'incidenza di un esito. Un metodo alternativo al calcolo della probabilita' e' il calcolo degli *odds*. Data la tabella di contingenza:

|Gruppo |Caso|Controllo|
|:---|:---|:---|
|Esposti|a|b|
|Non esposti|c|d|


>
>Odds di essere esposto tra i casi
>
>$$O1 = \frac{a}{c}$$
>
> Dove a e' il numero di casi esposti e c il numero di casi non esposti
>
> Odds di essere esposto tra i controlli
>
>$$O0 = \frac{b}{d}$$
>
> Dove c e' il numero di controlli esposti e d il numero di controlli non esposti
>

Per misurare l'associazione tra esposizione ed esito si pu' calcolare il rapporto degli odds ($OR$), chiamato anche **odds ratio**.

Lo *odds ratio* ($OR$) e':

$$ OR = \frac{ a / c }{b / d} $$

L'odds ratio indica di quante volte è più grande (o piu’ piccola) la probabilita' di esito nel gruppo esposto rispetto a quella nel gruppo non esposto. Come il rischio relativo, l'odds ratio quantifica la forza dell’associazione tra esposizione ed esito. Per valori bassi di rischio nel gruppo non esposto ($R0 <10%$), $OR$ da valori numericamente simili al $RR$.

**Intervallo di confidenza del OR**.
Analogamente al $RR$, anche con lo $OR$ si puo’ valutare se il valore osservato sul campione dei partecipanti allo studio possa derivare da una popolazione nella quale non ci sia associazione tra esposizione ed esito semplicemente controllando se il valore 1 e’ contenuto nell’intervallo di confidenza del $OR$. 

### Bias negli studi caso-controllo
Questi studi sono affetti da bias di selezione, informazione e confondimento analogamente agli studi di corte.

Tra i bias di selezione rientra il _bias di scorretta selezione dei controlli_. Questo errore e' presente quando i controlli sono selezionati da una popolazione diversa da quella dalla quale si sono selezionati i casi. Per es. possiamo selezionare i casi tra i pazienti di un reparto poco rinomato di un ospedale pubblico ed i controlli da una clinica privata dove opera un primario molto famoso. In questo ipotetico esempio e' probabile che la provenienza geografica dei pazienti "controllo", il loro livello socioeconomico e culturale sia diverso da quello dei casi inserendo delle differenze non dovute all'esposizione in studio.

Tra i bias di informazione piu' frequenti ricordiamo il _bias del ricordo_, presente quando l'esposizione viene attribuita retrospettivamente tramite questionari od interviste ai partecipanti lo studio. Per es. e' stato verificato che le madri di bambini con difetti alla nascita ricordino con piu' esattezza i farmaci che hanno assunto durante la gravidanza rispetto alle madri di bambini normali. Quindi i casi tendono a ricordare meglio eventuali esposizioni rispetto ai controlli. Il _bias dell'intervistatore_ si ha quando la persona che amministra il questionario pone le domande in maniera diversa (con maggiore/minore enfasi o con maggiore dettaglio) ai casi rispetto ai controlli.

Bias del confondimento: come per gli studi di corte deriva da caratteristiche dei soggetti che sono correlate sia con l'eposizione sia con l'esito e che ne modificano l'associazione. Per esempio in un ipotetico studio tra consumo di alcol e malattie cardiovascolari, il fumo di tabacco e' un confondente di cui bisogna tener conto. Una possibile strategia e' analizzare questa associazione in due sottogruppi omogenei rispetto al confondente (nei fumatori e nei non fumatori). 
   
### Vantaggi/svantaggi studi caso-controllo

Vantaggi:
- Efficienti per gli esiti rari o con lungo periodo di latenza
- Possono valutare associazioni tra malattia ed esposizioni multiple, per cui sono
indicati per malattie di cui si conosce poco
- Costo minore rispetto ai corte prospettici perche’ l’informazione su esiti ed esposizione e’ spesso gia’ disponibile

Svantaggi:
- Non efficienti per esposizioni rare
- Informazione su esposizione può essere fallace
- Non è possibile stimare l’incidenza di malatti

### Esempio studio caso-controllo
La carenza di staff in reparto aumenta il rischio di ICA nei pz in ter. int.?
la vostra ipotesi: meno staff -> maggiore carico di lavoro ->minore aderenza alle procedure di sicurezza -> maggiori rischi per il paziente
P: pazienti ricoverati in terapia intensiva per piu’ di 7gg da diversi ospedali
I: degenza durante periodo con staff sotto organico (<2 persone per paziente)
C: degenza durante periodo staff a pieno organico
O: Aver contratto l’infezione durante la degenza (ICA)
Fonte dei dati
esiti e date ricovero: registri di reparto/cartelle cliniche esposizione: ufficio del personale
   
 Infezione durante degenza
     si (caso)
No (controllo)
Staff sotto-organico
144
222
Staff non sotto- organico
92
348
 esposizione
  Odds di essere esposto tra I casi = 144/92 Odds di essere esposto tra I controlli = 222/348
OR = (144 / 92) / (222/348) = 2.45 (IC: 1.8 – 3.3)
Interpretazione:
I pazienti con degenza in terapia intensiva durante i periodi di sotto- organico hanno un rischio di 2.4 più elevato di sviluppare un infezione rispetto ai periodi con dotazione organica adeguata al reparto.
  
 dal pico alle intestazioni della tabella
P: I: C: O:
pz ricoverati in terapia intensiva per piu’ di 7gg staff sotto-organico
staff completo
ica
         sotto-organico
----------------
completo
----------------
ICA si
---------------
144
92
ICA no
---------------
222
348
  Odds Odds
casi
144/92
di essere esposto gruppo...................... = di
 essere esposto gruppo ....................... =
controllo
222/348
  
      
      
  Es8a rischio cadute e incontinenza
P = paziente ricoverato >75 anni I = incontinenza urinaria
C = continenza nella norma
O = esito
  incontinenza
Non incontinenza
7
54
Caduti (caso)
61
Non caduti (controllo)
3
67
70
 Odds essere incontinente tra caduti = 7 / 54 = 0.12 Odds essere incontinente tra i non caduti = 3 / 67 = 0.04
         
 P individui >75anni I alto BMI
C BMI normale
O rischio cadute
Odds esposizione tra casi = 13/6 = 2.16 odds esposizione tra controlli= 7/21 = 0.28
Es. 8b rischio fratture e BMI
    
## Gli studi trasversali (cross-sectional)
In EBN, gli studi trasversali vengono utilizzati per capire cosa hanno in comune (o cosa non hanno) i pazienti/ popolazioni studiate e come variano tra loro per la prevalenza dei fattori prognostici / di rischio. Questi studi servono a verificare nuove ipotesi eziologiche/prognostiche prima di intentare studi piu' complessi come gli studi di corte e gli atudi caso-controllo.

Sono esempi di studi trasversali le indagini su grandi campioni (survey) che hanno lo scopo di stimare la prevalenza di alcuni fattori di rischio e / o condizioni di salute all’interno della popolazione (o sottogruppi di essa). Gli studi KAP (dall’ inglese Knowledge, Attitude and Practice) sono indagini sulle conoscenze, attitudini e comportamenti riferite a particolari comportamenti o stili di vita come per es. l'esitazione vaccinale o la partecipazione alle campagne di screening oncologico.

### Descrizione

Si dicono trasversali perche' sia l'esposizione che l'esito sono misurati nello stesso momento (una sezione trsversale del tempo). Conseguentemente, non e’ possibile verificare che l’esposizione preceda l’evento.
{figura cross-sectional}

 tutto quello che c’e’ da sapere sui trasversali
• disegno studio trasversale
• risultati di uno studio trasversale: prevalenza, RP
• principali errori sistematici (bias) degli studi trasversali
• valutazione critica studi trasversali

**Le survey (indagini campionarie)**.
Gli studi Cross-sectional comprendono le survey o indagini campionarie. E’ un’indagine effettuata su tante persone, selezionate con rigorose tecniche di campionamento, in una normale situazione di vita, utilizzando procedure standardizzate, in grado di produrre misure quantitative e in cui ci si propone di analizzare le relazioni tra le variabili implicate. E' spesso necessario effettuare un campionamento di tipo statistico.

**Il campionamento casuale semplice**.
Raramente negli studi di prevalenza vengono inclusi tutti gli individui di una popolazione. Il campionamento deve assicurare la rappresentativita’, ovvero i soggetti inclusi devono rappresentare la popolazione per la quale si vuole generalizzare la stima. Il campionamento probabilistico (casuale semplice) prevede la selezione casuale dei partecipanti da una lista comprendente tutta la popolazione. Per es. in uno studio condotto su gli infermieri in servizio, potremmo selezionare a caso degli infermieri da una lista del personale infermieristico in servizio presso una azienda ospedaliera. Quando invece non si utilizza uno schema di campionamento probabilistico, la prevalenza viene campionata su un **campione di convenienza**. Per es. potremmo selezionare gli infermieri partecipanti tramite le conoscenze del nostro capo reparto. In questo caso le conclusioni del nostro studio non potranno essere generalizzate alla popolazione di tutti gli infermieri dell'azienda ospedaliera ma restano valide se ristrette al campione esaminato.

### Risultati degli studi trasversali

Gli studi trasversali hanno spesso l'obiettivo di stimare la **prevalenza** di una patologia o di una fattore di rischio all'interno di una popolazione.

$$Prevalenza = \frac{numero\ \ casi\ \ }{popolazione}$$

Si noti che per stimare la prevalenza non c'e' bisogno di un periodo di followup. Per questo motivo e' rifarita al momento in cui si effettua la misura. Per es. la prevalenza dei pz che sono caduti in reparto in una settimana sara' uguale alla somma dei pz che sono caduti in quella settimana sulla somma dei pazienti presenti in quel reparto.

La tabella di contigenza nel caso di esposizione ed esito entrambe quantificate mediante variabili dicotomiche e':

|Gruppo |Esito|Non Esito|Tot|
|:---|:---|:---|:---|
|Esposti|a|b|a+b|
|Non esposti|c|d|c+d|
|Tot |a+c|b+d|a+b+c+d|


Da cui segue che:

>
>Prevalenza nel gruppo esposto 
>
>$$P1 = \frac{a}{(a+b)}$$
>
> Dove a e' il numero di casi nel gruppo esposto e (a+b) e' il numero di individui totale nel gruppo esposto
>
> Prevalenza nel gruppo non esposto
>
>$$P0 = \frac{c}{(c+d)}$$
>
> Dove c e' il numero di casi nel gruppo di non esposto e (c+d) e' il numero di individui totale nel gruppo non esposto
>

Per misurare l'associazione tra esposizione ed esito si puo' calcolare il rapporto delle prevalenze ($RP$) analogamente al rischio relativo.

Il *rapporto di prevalenza* ($RP$) e':

$$ RP = \frac{ P1 }{P0}$$

Dove:

P1: Prevalenza esito nel gruppo esposto

P0: Prevalenza esito nel gruppo non esposto

Indica di quante volte è più grande (o piu’ piccola) la prevalenza di esito nel gruppo esposto rispetto a quella misurata nel gruppo non esposto. Come per il rischio ralativo e l'odds ratio e' possibile calcolare l'intervallo di confidenza.

In alternativa, quando il campione e' di convenienza, per misurare l'associazione tra esposizione ed esito si preferisce calcolare il rapporto degli odds ($OR$) 

$$ OR = \frac{ a / c }{b / d} $$

L'odds ratio indica di quante volte è più grande (o piu’ piccola) l'odds di avere l'esito nel gruppo esposto rispetto a quella nel gruppo non esposto. 



### Bias negli studi trasversali
Il bias piu' importante e' il **bias temporale**. Infatti, misurando sia esposizione che esiti nello stesso momento non si e’ sicuri che l’esposizione preceda l’esito. Questo bias non e' presente quando si e' ragionevolmente certi che l'esposizione abbia preceduto l'esito, come per es. nelle associazioni tra fattori di rischio genetici ed esito.

Come per gli altri disegni analitici sono presenti diversi tipi di *bias di informazione*, come errori nell’attribuzione dell’esposizione (specialmente se attribuita retrospettivamente tramite questionari) o errori nella determinazione dell’esito. Il *bias di selezione ricorre* per es. quando viene effettuato uno scorretto campionamento (per es. campionamento di convenienza) ma poi si generalizzano i risultati alla popolazione sottostante. Infine, va sempre considerata l'eventuale presenza nello studio di *fattori di confondimento*.

### vantaggi/svantaggi studi trasversali
Il principale vantaggio degli studi trasversali e' che sono studi di facile esecuzione e spesso poco dispendiosi in termini di tempo. E’ possibile calcolare la prevalenza di patologie e fattori di rischio in sottogruppi della popolazione e stabilire una associazione tra esposizione e malattia con il rapporto di prevalenza o con l'odds ratio. Sono quindi studi adatti a monitorare lo stato di salute all'interno di una popolazione.

Tra gli svantaggi, se lo studio prevede un campionamento probabilistico questo puo' essere complicato da realizzarsi. Non sono generalmente adatti a testare ipotesi eziologiche perche’ non si riesce a determinare con certezza che l’esposizione abbia preceduto l’esito. 
   
### Esempio studio trasversale

**Esempio: turno di notte e livello di stress**
Si ipotizza che il personale infermieristico che svolge con frequenza il turno di notte abbia un livello di stress percepito maggiore rispetto a chi invece svolge il turno di notte con meno frequenza.
Decidi di effettuare uno studio trasversale per vedere se l’ipotesi e’ valida e puo’ poi essere verificata con studi piu’ lunghi e complessi (corte o caso controllo)
P: infermiere in servizio presso ospedali I: svolge spesso turno notte
C: svolge raramente turno notte
O: sintomi di stress psicologico
   
 Esempio
Ottieni la lista dei dipendenti da 16 ospedali pubblici che servono centri abitati di simile dimensioni.
Estrai un campione casuale al quale sottoponi un questionario con una scala validata per la misura dello stress lavoro correlato.
Ottieni per gli stessi individui dalla direzione sanitaria i records di servizio.
Li dividi tra chi effettua il turno di notte >=10 gg al mese e <10gg al mese.
   
 Esempio
 Malati Alto stress
  ESPOSTI Turno di notte spesso
n.570
56
   Campione casuale: 1148 infermieri dalla lista dei dipendenti di 16 ospedali
 Non malati Assenza sintomi stress
 514
 malati Alta livello stress
 NON ESPOSTI
Turno di notte raramente n.578
  Non malati assenza sintomi stress
24
  554
   
 Esempio calcolo rapporto prevalenze
stress +-
 56
514
24
554
Esposizione (turno di notte)
+ -
tot
570
578
1148
= 56/(570) 24/(578)
   RP =
Prevalenza negli esposti
Prevalenza nei non esposti
= 2.1
  Interpretazione: la prevalenza dei sintomi di stress psicologico lavoro correlato e’ 2.1 volte piu’ elevata tra coloro che svolgono il turno di notte >= 10 volte al mese e coloro che lo svolgono <10 volte al mese.
  
 uso di OR come misura di associazione tra esposizione ed esito
stress +-
 56
514
24
554
Esposizione (turno di notte)
56 x 554 24 x 514
+ -
= 2.5
tot
570
578
1148
   OR =
 Negli studi cross sectional OR viene usato piu’ spesso perche’ piu’ facile da calcolare in forma aggiustata nell’analisi multivariata.
OR e’ una buona approssimazione di RP se la prevalenza nei non esposti e’ bassa (< 10%)
  
 Es8a dipendenza smartphone
P- (scolaro) adolescente
I- bassa autostima
C- autostima normale
O- dipendenza da smartphone
   08/02/21
74
   
 Es8a dipendenza smartphone
RP
La prevalenza della dipendenza da smartphone negli adolescenti con bassa autostima e’ 1.6 volte la prevalenza di quelli con autostima normale
OR
la probabilita’ di essere dipendente da smartphone nel gruppo con bassa autostima e’ 3.2 volte quella del gruppo con autostima normale
L’autostima sembra associata con la dipendenza da smartphone
Problemi: non sono sicuro che l’autostima causi la dipendenza perche’ l’esposizione e l’esito (dipendenza da smartphone) sono misurate nello stesso momento. Possono esserci molte altre variabili che incidono con il risultato. Diverse scuole, diversi contesti socio economici.
 08/02/21
75
  
 Es8b sonno e comfort letto
E’ stata condotta un’indagine trasversale sulla qualita’ del sonno autoriportata in un campione di pazienti ricoverati in 10 reparti con lo scopo di individuare i principali determinanti della qualita’ del sonno. Su un totale di 157 pazienti, 136 hanno riportato una scarsa qualita’ del sonno. Il numero di pazienti divisi per qualita’ del sonno e le principali cause indicate sono riportate in tabella.
    Qualita' sonno
BASSA
ALTA
comfort letto no
106
14
comfort letto si
      08/02/21
76
  
 Esercizio studio cross sectional
P- pazienti ricoverati in 10 reparti I- no comfort letto
C- comfort letto
O- qualita’ sonno
 08/02/21
77
  
 Discomfort letto – qualita’ sonno
    08/02/21
78
  
 Dolore- qualita’ sonno
    08/02/21
79
  
 Preoccupazione-qualita’ del sonno
   08/02/21
80
   
 Esercizio studio cross sectional
Discomfort letto non e’ un determinante significativo della cattiva qualita’ del sonno mentre lo sono preoccupazione e dolore.
Intervalli confidenza grandi: ampia variabilita’ (sesso, reparti, eta’, diagnosi...)
Bias: nessuna informazione su qualita’ del sonno a casa, bias di selezione, confondenti non misurati (quali?)
Suggerimenti : fare studio di corte (o caso-controllo) sull’associazione tra un fattore per volta e qualita’ sonno
 08/02/21
81
  
## Case reports, case series
Case report: dettagliata descrizione di segni e sintomi o risultati di laboratorio relativi ad un “caso tipico” od un piccolo gruppo di casi. Case series uniscono piu’ case report
Scopo: segnalare alle autorita’ sanitarie ed alla comunita’ scientifica casi sospetti, nuove malattie o possibili epidemie.
Vantaggi: rapida diffusione dei risultati
Svantaggi: Studi privi di un protocollo di raccolta dati e (spesso) di rigore metodologico.
Es. Un clinico riporta di una malattia inusuale o di una strana associazione
        
## Validita’ interna studi analitici
Per stabilire se uno studio analitico (corte, caso-controllo o trasversale) sia valido si ricorre alle check list come per gli studi sperimentali. In termini generali gli aspetti da verificare sono inerenti la validita' interna (assenza di errori sistematici), la significativita' e l'applicabilita' clinica dei risultati dello studio.

Per esempio domanti rilevanti la validita' interna sono:

- Il campione di pazienti era rappresentativo del decorso della malattia?

- La durata e completezza del follow up erano adeguati?

- Esiti (nei corte) verificati in cieco (senza conoscere se il soggetto faceva parte del gruppo esposto o non esposto) dove possibile?

- Esposizione (nei caso-controllo) verificata in cieco dove possibile?

- Assenza di bias di selezione e di informazione?

- Assenza di bias di confondimento: e’ stata effettuata analisi stratificata?

Domande rilevanti per la significativita’ clinica sono:

- la dimensione dell’effetto dell’esposizione e’ clinicamente rilevante?

- quanto e’ precisa la stima dell’esposizione?

Domande rilevanti per l'applicabilita’ clinica sono:

- la popolazione di pz nel mio reparto e’ sufficientemente simile a quelli considerati nello studio?

- il setting assistenziale del mio reparto e’ sufficientemente simile a quello dello studio?


### Esercizi

   
