# Review sistematiche e metanalisi
Le revisioni sistematiche sono degli studi secondari condotti come dei veri e propri progetti di ricerca che sintetizzano e valutano criticamente in un unico documento gli esiti di tutti gli studi primari riguardo ad un determinato e ben definito quesito clinico o intervento infermieristico. Per un certo quesito EBN, ci danno anche un’idea della consistenza delle evidenze prodotte da tutti gli studi effettuati (per es. quanti di questi hanno rilevato differenze di efficacia tra due trattamenti). Per questo motivo sono studi estremamente utili e significativi nella pratica EBN. In generale, e' sempre preferibile per un dato quesito ricercare meta-analisi che siano recenti e di buona qualita' prima di passare, se non ne esistono, all'esame dei risultati di studi primari.
  
Una revisione tradizionale della letteratura e' un articolo scientifico in cui gli autori fanno il punto sulle attuali conoscenze su un determinato argomento. Non segue nessuna regola formale e ha ampie finalità. Al contrario, una revisione sistematica è una revisione della letteratura condotta seguendo un protocollo formale e standardizzato.La meta-analisi è una revisione sistematica che prevede anche un' analisi statistica finalizzata alla combinazione dei risultati di diversi studi in un’unica statistica riassuntiva.
  
## Descrizione

Le fasi metodologiche di una meta-analisi sono:

**1. Definizione del quesito di ricerca**. E' utile definire il quesito di ricerca utilizzando il metodo PICOM, dova la M definisce il tipo di studi che andiamo a considerare (sperimentali, corte, caso-controllo ecc.). Per il resto sono valide le considerazioni gia' fatte nei capitoli precedenti.

**2. Definizione dei criteri di inclusione degli studi**. Quali studi includere dipende dal tipo di quesito. Di solito per quesiti di trattamento si includono gli studi sperimentali, per eziologici e prognostici gli studi corte , caso controllo, per i quesiti di diagnosi si includono gli studi trasversali. Di solito si tende ad inserire studi dello stesso tipo. Devono poi essere eplicitati la tipologia del trattamento (intervento di interesse) o l'esposizione (nel caso di studi osservazionali), le caratteristiche dei pazienti e dell'esito studiato.

**3. Ricerca bibliografica**. Viene effettuata sulle banche dati biomediche. La strategia di ricerca ideale è quella che consente di reperire, su scala internazionale, tutti gli studi, pubblicati e non, che riguardano l’argomento della revisione. Per garantire un elevata completezza, le ricerche devono essere condotte considerando molte e diverse fonti: database elettronici (Medline, Embase, Cinhal, etc), registri nazionali ed internazionali, bibliografie delle review e delle monografie sull’argomento, bibliografie degli studi individuati, records collegati agli studi selezionati. La stringa di ricerca deve essere esplicitata nel protocollo dello studio.  Gli studi vengono selezionati sulla base prima del titolo, poi dell'abstract ed infine dopo la lettura del full text. In ogni fase vengono eliminati gli studi che non sono conformi ai criteri di inclusione.

**4. Valutazione della qualita’ metodologica degli studi**. Esistono diversi metodi standardizzati per la valutazione “quantitativa” della qualita’ dei trial clinici (es. scala jadad) e degli studi osservazionali. La valutazione e' di solito effettuata in duplicato da due componenti del gruppo di ricerca. In caso di non accordo nello score di qualita' per uno studio particolare tra i due valutatori, si ottiene il giudizio consensuale.  La valutazione della qualita’ metodologica degli studi individuali va fatta sempre.

**5. Estrazione e presentazione dei dati**. Estraggo la misura di effetto e il suo intervallo di confidenza. Negli studi di trattamento quindi estrarremmo il rischio relativo o la differenza dei rischi o la differenza delle medie, negli studi di corte il rischio relativo, negli studi caso-controllo e negli studi trasversali l'odds ratio. Negli studi diagnostici Sensibilita', specificita' e valori predittivi.

**6. Combinazione statistica dei dati e rappresentazione grafica**. Le stime di efficacia dei vari studi selezionati vengono combinate insieme in un unica misura combinata ("pooled") che tiene conto dei contributi in termini di numerosita' dei pazienti di tutti gli studi. Il risultato di uno studio con tanti pazienti pesera’ piu’ nel valore combinato finale che un risultato derivante da uno studio piccolo. 
La visualizzazione viene effettuata mediante il forest plot. Ogni studio e’ riportato graficamente con il suo RR oppure con OR e ha sempre associato il suo intervallo di confidenza. Se l’intervallo comprende la linea di no effect (OR oppure RR = 1), vuol dire che non c’e’ effetto significativo. La prima colonna riporta il nome dello studio; la parte grafica della figura riporta la stima dell’effetto per ciascuno studio, sotto forma di quadrato nero. La linea verticale rappresenta l’assenza di differenze, ovvero il valore nullo della misura di associazione (RR=1, RD=0, OR=1). La dimensione del quadrato dipende dalla numerosità dello studio: i quadrati di dimensioni maggiori indicano che la stima è stata calcolata su campioni elevati, e dunque dovranno ricevere maggiore peso rispetto alle stime calcolate su piccoli campioni. Ogni quadrato è attraversato da una barra orizzontale che rappresenta l'intervallo di confidenza. La colonna “peso” esprime il peso in percentuale che ciascuno studio ha avuto nella metanalisi. La stima globale fornita dalla metanalisi è rappresentata dal simbolo a losanga riportata sotto le stime dei singoli studi e indica anche l'intervallo di confidenza. 
{figura forest plot}

**7. Analisi di sensibilita’**. La stima conbinata viene ripetuta su sottogruppi omogenei di studi.

## Principali bias delle meta-analisi
Scorretta ricerca (errore nella stringa di ricerca) e selezione degli articoli. Assenza di valutazione della qualita’ dei singoli studi.

Eterogeneita’ nei singoli studi

Bias di pubblicazione
   
Valutazione qualita’ singoli studi
Non tutti gli studi sono di buona qualita’. Si deve valutare la validita’ interna di ciascuno studio selezionato per la meta-analisi (assenza di errori random e bias).

Esistono degli strumenti specifici per ciascuna tipologia di studio
   
Eterogeneita’ dei risultati dei singoli studi

Presenza di eterogeneita’ nei singoli lavori: i valori di RR oppure di OR dei singoli studi sono troppo diversi per essere combinabili in un’unica stima combinata

Bias di pubblicazione: solo gli studi nei quali si sono osservati risultati favorevoli al trattamento sperimentale vengono pubblicati, e quindi inseriti nella metanalisi.
Invece quelli nei quali non si sono osservati effetti favorevoli non vengono pubblicati e quindi non sono presenti nelle banche dati. Questo vuol dire la stime combinate verra’ distirta a favore del trattamento.
Di solito gli studi che non danno risultati significativi sono quelli con scarsa potenza statistica, ovvero quelli con pochi pazienti reclutati
   

## Esempio
I risultati si riportano graficamente mediante il forest plot
es. metanalisi per verificare se la clorexidina e’ un trattamento piu’ efficace per evitare infezioni del sito chirurgico nel pz operato all’addome rispetto allo iodopovidone?
P: pz operato all’addome
I: trattamento ferita con clorexidina
C: trattamento ferita con iodopovidone O: infezione sito chirurgico
M: studi sperimentali
   
 Esempio risultati di una metanalisi (forest plot)
 Ogni linea e’ il valore dell’effetto (in questo esempio tramite RR) misurato in un singolo studio
Corrigan (2000)
Shrader (2000)
Linea di RR=1: (Assenza di effetto)
Dimensione del quadrato proporzionale alla numerosita’ dei pz
1.31 (0.75-2.27)
0.66 (0.51-0.87)
        Sull’asse x c’e’ l’intensita’ della misura di effetto (in questo esempio RR)
0.5
1
1.5
 A favore del trattamento di sperimentale (clorexidina)
A favore del trattamento controllo (iodopovidone)
  
 Linea di RR=0.85 (valore pooled)
Peso dello studio nel calcolo (proporzionale alla numerosita’ dei pz)
Esito RR (IC95%)
     Stima RR combinato, media pesata degli RR di tutti gli studi.
A favore del trattamento di sperimentale
A favore del trattamento controllo (iodopovidone)
   (clorexidina)
  
 Conclusione della meta-analisi?
Si esamina il valore della misura combinata ed il suo intervallo di confidenza
Es: il valore del RR combinato indica una maggiore efficacia del trattamento della ferita chirurgica con clorexidina rispetto allo iodopovidone nella prevenzione delle infezioni del sito chirurgico post- operazione all’addome
   
     
## Esercizi     
      
      
      
      
 Es10a calze antitrombo
P: individui >75 anni che devono affrontare un lungo viaggio (>3h senza soste)
I: calze antitrombo
C: nessun presidio
O: trombosi venosa profonda M: caso-controllo
• Quale misura di effetto? OR = a/c / b/d
• Maggiore rischio salute? studio n1 (OR=2.9)
• Minore rischio per la salute? studio n3, n6 (OR=0.3)
• Non c’e’ evidenza di effetto? studi 2,3,4,5
• Peso maggiore: studio 4 perche’ al maggiore numero di soggetti reclutati
• Maggiore variabilita’: studio 3 perche’ ha l’intervallo di confidenza piu’ ampio
• Il rischio complessivo OR pooled = 1.5 (0.8, 2.7); concludo che le calze non servono a prevenire la trombosi venosa profonda
• Bias: assenza valutazione qualita’, diverse popolazioni studiate (pazienti immo
 bilizzati e viaggiatori) , eterogeneita’ nei risultati
  
